name: jest
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  jest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: "./.github/actions/setup-node"
      - run: yarn --frozen-lockfile
      - run: yarn test
