name: prettier
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 18
      - run: yarn --frozen-lockfile
      - run: yarn prettier
