name: textlint
on: [pull_request]
jobs:
  textlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: reviewdog/action-setup@v1
      - run: reviewdog -version
      - run: npm install --ignore-scripts
      - run: |
          npx textlint -f checkstyle 'docs/**/*.md' \
            | reviewdog -f=checkstyle -name="textlint" -reporter=github-pr-review
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
